###############
## 
####

GPU: [0,1]

VERBOSE: True

MODEL:
  MODE: 'Deraining'
  SESSION: 'LDRCNet'

# Optimization arguments.
OPTIM:
  BATCH_SIZE: 8
  NUM_EPOCHS: 300
  # NEPOCH_DECAY: [10]
  #LR_INITIAL: 2e-4
  LR_INITIAL: 3e-4
  LR_MIN: 1e-6
  # BETA1: 0.9

TRAINING:
  VAL_AFTER_EVERY: 4
  RESUME: True
  TRAIN_PS: 256
  VAL_PS: 128
  #VAL_PS: 256
  TRAIN_DIR: '/home/cls2022/hyh/data/Rain13K/train'       # path to training data
 # VAL_DIR: './Datasets/test/Rain100L' # path to validation data
  VAL_DIR: '/home/cls2022/hyh/data/Rain13K/test'
  SAVE_DIR: '/home/cls2022/hyh/MPRNet/checkpoints'           # path to save models and images
  # SAVE_IMAGES: False
